name: Code Quality

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.0'

      - name: golangci-lint
        id: lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: latest
          args: --timeout=5m
        continue-on-error: true

      - name: Create Issue on Lint Failure
        if: steps.lint.outcome == 'failure'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            let title = '[BUG] Workflow 检测失败: 代码质量检查失败';

            let body = `## 错误描述\nCI/CD 流程中检测到代码质量检查失败。\n\n`;

            body += `## 复现步骤\n1. 查看 [工作流运行](${process.env.GITHUB_SERVER_URL}/${process.env.GITHUB_REPOSITORY}/actions/runs/${process.env.GITHUB_RUN_ID})\n\n`;

            body += `## 环境\n- 工作流: ${process.env.GITHUB_WORKFLOW}\n- 提交: ${process.env.GITHUB_SHA}\n- 分支: ${process.env.GITHUB_REF}\n\n`;

            body += `## 附加上下文\n此问题由 GitHub Actions 工作流自动创建。`;

            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: title,
              body: body,
              labels: ['bug', 'automated', 'code-quality']
            });
