name: Wiki Sync

on:
  push:
    branches: [ main, master ]
    paths:
      - '.github/wiki-template/**'
  workflow_dispatch:

jobs:
  sync-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          path: source
          
      - name: Checkout wiki
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}.wiki
          path: wiki
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Sync wiki content
        run: |
          # Copy all files from wiki-template to wiki
          cp -r source/.github/wiki-template/* wiki/
          
          # Configure git in wiki directory
          cd wiki
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          # Add, commit and push changes
          git add .
          git diff --staged --quiet || git commit -m "Update wiki content from wiki-template"
          git push